### ISSUE TITLE
Error on NextJS implementation -> ReferenceError: self is not defined 

### ISSUE THREAD

**Issue by z33bs** [dimazuien/react-viewport-height#211]
**Describe the bug**
Has desired effect, renders correctly... but in development mode get the following error (below). I'm worried that it might cause unexpected issues in production.

error - node_modules/react-viewport-height/lib/index.js (1:228) @ eval
error - ReferenceError: self is not defined

I don't find the stack trace too enlightening... not sure what's going on tbh

Error shows on chrome, firefox and safari as well as safari on iphone

**Comment by dimazuien** [comment]
@z33bs, could you provide more details: OS, node version, node module dependencies used, specific features of the project if any (e.g. SSR), etc.?
